name: Build Godot Game

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      platform:
        description: 'Choose platform to build'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - Linux
          - Windows Desktop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ${{ github.event.inputs.platform == 'all' && ['Linux', 'Windows Desktop'] || [github.event.inputs.platform] }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Godot
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: Debugged
          preset: ${{ matrix.platform }}
          debugMode: "false"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debugged - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
