name: Build Godot Game

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      platform:
        description: 'Choose platform to build'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - Linux
          - Windows Desktop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["Linux", "Windows Desktop"] 

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Create export directories
        run: mkdir -p build/Linux build/Windows
      - name: Build Godot
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: Debugged
          preset: ${{ matrix.platform }}
          debugMode: "false"

      - name: Set folder name
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" = "Windows Desktop" ]; then
            echo "FOLDER=Windows" >> $GITHUB_ENV
          else
            echo "FOLDER=Linux" >> $GITHUB_ENV
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debugged - ${{ matrix.platform }}
          path: build/${{ env.FOLDER }}
